# Generated by Django 2.2.1 on 2019-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191105_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('exam_id', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='examcreatedetails',
            index=models.Index(fields=['username', 'email_id'], name='exam_examcr_usernam_89bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='examcreatedetails',
            index=models.Index(fields=['username'], name='user_name_idx'),
        ),
    ]
