# Generated by Django 2.2.1 on 2019-12-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20191214_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
