# Generated by Django 2.2.1 on 2019-12-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20191214_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('question_number', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('exam_date', models.DateTimeField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamCreateDetails', to_field='exam_id')),
            ],
        ),
    ]
